services:
  mongodb_main:
    container_name: mongodb_main
    extends:
      file: docker-compose.common.yml
      service: mongodb
    volumes:
      - mongodb_data:/data/db

  nestjs_app_main:
    container_name: nestjs_app_main
    extends:
      file: docker-compose.common.yml
      service: nestjs_app
    environment:
      MONGO_HOST: mongodb_main
      LOG_LEVEL: log
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        npx nest start --entryFile main.seeder
        yarn start:prod
    depends_on:
      - mongodb_main

volumes:
  mongodb_data:
