version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  nestjs_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://root:example@mongodb:27017/nestjs_app

volumes:
  mongodb_data:
