services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_AUTH_DB_USERNAME: ${MONGO_AUTH_DB_USERNAME}
      MONGO_AUTH_DB_PASSWORD: ${MONGO_AUTH_DB_PASSWORD}
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - ./scripts/mongo/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  nestjs_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MONGO_PORT: 27017
      MONGO_AUTH_DB_USERNAME: ${MONGO_AUTH_DB_USERNAME}
      MONGO_AUTH_DB_PASSWORD: ${MONGO_AUTH_DB_PASSWORD}
      PORT: ${PORT}
    ports:
      - '${PORT}:${PORT}'
