name: Main CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run Docker container
        run: |
          cp env/.env.example .env
          docker-compose up -d

      - name: Run unit tests
        run: |
          docker-compose exec -T nestjs_app_main yarn test

      - name: Run integration tests
        run: |
          docker-compose --env-file env/.test.env -f docker-compose.test.yml up nestjs_app_test

      - name: Shutdown Docker container
        run: |
          docker-compose -f docker-compose.test.yml down mongodb_test -v
          docker-compose down -v
